name: Check links

on:
  push:
  pull_request:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the documentation
        run: |
          pip install requirements.txt
          sphinx-build . _build/html

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.2.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          args: _build/**/*.html
